locals {
  config = {
    cert_manager = "${module.dns.config}"
    externaldns  = "${module.dns.config}"
    gangway      = "${module.gangway.config}"
  }
}

output "config" {
  value = "${jsonencode(local.config)}"
}

output "kubeconfig_command" {
  value = "cp infrastructure/amazon/kubeconfig_cluster-${random_id.suffix.hex} $$KUBECONFIG"
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = "${module.cluster.kubeconfig}"
}
