locals {
  config = {
    cert_manager = "${data.external.cert_manager.result}"
    externaldns  = "${data.external.externaldns.result}"
    gangway      = "${module.gangway.config}"
  }
}

output "config" {
  value = "${jsonencode(local.config)}"
}

output "kubeconfig_command" {
  value = "cd infrastructure/digitalocean/ && terraform output kubeconfig > $$KUBECONFIG"
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = "${module.cluster.kubeconfig}"
}
